/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пульс API */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/vk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Vk */
        post: operations["auth_vk_api_v1_auth_vk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/faq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Faq Items
         * @description Получить опубликованные вопросы с фильтром и пагинацией.
         */
        get: operations["list_faq_items_api_v1_content_faq_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/faq/{faq_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Faq Item
         * @description Получить один опубликованный вопрос по идентификатору.
         */
        get: operations["get_faq_item_api_v1_content_faq__faq_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List News Posts
         * @description Получить опубликованные новости с фильтрами и пагинацией.
         */
        get: operations["list_news_posts_api_v1_content_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/news/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get News Post
         * @description Получить полное содержимое одной опубликованной новости.
         */
        get: operations["get_news_post_api_v1_content_news__news_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedule Events
         * @description Получить опубликованные события программы с фильтрами и пагинацией.
         */
        get: operations["list_schedule_events_api_v1_content_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/schedule/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule Event
         * @description Получить одно опубликованное событие по идентификатору.
         */
        get: operations["get_schedule_event_api_v1_content_schedule__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants/supporters/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Рейтинг народной поддержки
         * @description Топ участников по числу болельщиков с динамикой за сутки.
         */
        get: operations["supporters_rating_api_v1_participants_supporters_rating_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список участников
         * @description Список участников с фильтрами, сортировкой и пагинацией.
         */
        get: operations["list_participants_api_v1_participants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка участника */
        get: operations["get_participant_api_v1_participants__participant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants/{participant_id}/supporters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Счётчик болельщиков */
        get: operations["get_supporters_api_v1_participants__participant_id__supporters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants/{participant_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Нажать «Болею за» (идемпотентно) */
        post: operations["favorite_add_api_v1_participants__participant_id__favorite_post"];
        /** Убрать «Болею за» */
        delete: operations["favorite_remove_api_v1_participants__participant_id__favorite_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description Ответ на успешный вход через VK ID.
         */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserProfile"];
            /** Is New User */
            is_new_user: boolean;
        };
        /**
         * FAQItemResponse
         * @description Опубликованный вопрос - ответ для публичного API.
         */
        FAQItemResponse: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Category */
            category?: string | null;
            /** Order Index */
            order_index: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FAQListResponse
         * @description Страница опубликованных вопросов с данными пагинации.
         */
        FAQListResponse: {
            /** Items */
            items: components["schemas"]["FAQItemResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * FavoriteResponse
         * @description Ответ на «Болею за» / отписку.
         */
        FavoriteResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Created
             * @default false
             */
            created: boolean;
            /** Supporters Count */
            supporters_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NewsPostListItemResponse
         * @description Короткая карточка новости для ленты.
         */
        NewsPostListItemResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Lead */
            lead?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            source: components["schemas"]["NewsSource"];
            /** Stage Id */
            stage_id?: number | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Is Important */
            is_important: boolean;
            /** Is Pinned */
            is_pinned: boolean;
        };
        /**
         * NewsPostListResponse
         * @description Страница новостей с метаданными offset-пагинации.
         */
        NewsPostListResponse: {
            /** Items */
            items: components["schemas"]["NewsPostListItemResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * NewsPostResponse
         * @description Полная опубликованная новость.
         */
        NewsPostResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Lead */
            lead?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            source: components["schemas"]["NewsSource"];
            /** Stage Id */
            stage_id?: number | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Is Important */
            is_important: boolean;
            /** Is Pinned */
            is_pinned: boolean;
            /** Body */
            body: string;
            /** Vk Url */
            vk_url?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * NewsSource
         * @enum {string}
         */
        NewsSource: "manual" | "vk";
        /**
         * ParticipantDetail
         * @description Полная карточка участника.
         */
        ParticipantDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Number */
            number: number;
            /** Region */
            region?: string | null;
            /** Discipline */
            discipline?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            status: components["schemas"]["ParticipantStatus"];
            /** Dogs Count */
            dogs_count?: number | null;
            /** Bio */
            bio?: string | null;
            /**
             * Supporters Count
             * @default 0
             */
            supporters_count: number;
        };
        /**
         * ParticipantListItem
         * @description Короткая карточка участника для списка.
         */
        ParticipantListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Number */
            number: number;
            /** Region */
            region?: string | null;
            /** Discipline */
            discipline?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            status: components["schemas"]["ParticipantStatus"];
            /** Dogs Count */
            dogs_count?: number | null;
            /**
             * Supporters Count
             * @default 0
             */
            supporters_count: number;
        };
        /**
         * ParticipantStatus
         * @enum {string}
         */
        ParticipantStatus: "registered" | "active" | "finished" | "withdrawn" | "disqualified";
        /**
         * ParticipantSupporters
         * @description Счётчик болельщиков участника.
         */
        ParticipantSupporters: {
            /** Participant Id */
            participant_id: number;
            /** Supporters Count */
            supporters_count: number;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
        };
        /**
         * ScheduleEventListResponse
         * @description Страница событий программы с данными пагинации.
         */
        ScheduleEventListResponse: {
            /** Items */
            items: components["schemas"]["ScheduleEventResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ScheduleEventResponse
         * @description Опубликованное событие программы для публичного API.
         */
        ScheduleEventResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            kind: components["schemas"]["ScheduleKind"];
            /** Stage Id */
            stage_id?: number | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScheduleKind
         * @description Виды событий в программе фестиваля
         * @enum {string}
         */
        ScheduleKind: "race" | "cultural" | "other";
        /**
         * SupporterRatingEntry
         * @description Строка рейтинга народной поддержки.
         */
        SupporterRatingEntry: {
            /** Participant Id */
            participant_id: number;
            /** Name */
            name: string;
            /** Number */
            number: number;
            /** Supporters Count */
            supporters_count: number;
            /**
             * Delta 24H
             * @default 0
             */
            delta_24h: number;
        };
        /**
         * UserProfile
         * @description Профиль пользователя в ответе API.
         */
        UserProfile: {
            /** Id */
            id: number;
            /** Vk User Id */
            vk_user_id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Notifications Allowed */
            notifications_allowed: boolean;
        };
        /**
         * VKAuthRequest
         * @description Запрос на вход через VK ID.
         *
         *     `params` — все launch_params от VK Bridge, включая sign.
         *     `user_info` — имя/фото из VKWebAppGetUserInfo (VK Bridge).
         */
        VKAuthRequest: {
            /**
             * Params
             * @description Все launch_params VK, включая sign
             */
            params: {
                [key: string]: unknown;
            };
            /** @description Имя и фото из VKWebAppGetUserInfo */
            user_info?: components["schemas"]["VKUserInfo"] | null;
        };
        /**
         * VKUserInfo
         * @description Имя и фото из VKWebAppGetUserInfo (VK Bridge).
         */
        VKUserInfo: {
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /** Photo 200 */
            photo_200?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_vk_api_v1_auth_vk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VKAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_faq_items_api_v1_content_faq_get: {
        parameters: {
            query?: {
                category?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_faq_item_api_v1_content_faq__faq_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_posts_api_v1_content_news_get: {
        parameters: {
            query?: {
                source?: components["schemas"]["NewsSource"] | null;
                stage_id?: number | null;
                important_only?: boolean;
                published_from?: string | null;
                published_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsPostListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_post_api_v1_content_news__news_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsPostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedule_events_api_v1_content_schedule_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ScheduleKind"] | null;
                stage_id?: number | null;
                starts_from?: string | null;
                starts_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_event_api_v1_content_schedule__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supporters_rating_api_v1_participants_supporters_rating_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupporterRatingEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_api_v1_participants_get: {
        parameters: {
            query?: {
                /** @description Поиск по имени */
                search?: string | null;
                discipline?: string | null;
                status?: components["schemas"]["ParticipantStatus"] | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_api_v1_participants__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supporters_api_v1_participants__participant_id__supporters_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantSupporters"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favorite_add_api_v1_participants__participant_id__favorite_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favorite_remove_api_v1_participants__participant_id__favorite_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
